"""
常量表
"""


# 客户端请求
CLIENT_MSG_TYPE_LOGIN_OUT = -1
CLIENT_MSG_TYPE_LOGIN_IN = 0
CLIENT_MSG_TYPE_SINGLE_MSG = 2
CLIENT_MSG_TYPE_CHANGE_NICKNAME = 3
CLIENT_MSG_TYPE_CHANGE_SETTING = 4
CLIENT_MSG_TYPE_REQUEST_HISTORY = 5

# 服务端发送
SERVER_MSG_TYPE_ERROR_MSG = -1
SERVER_MSG_TYPE_LOGIN_INFO = 0
SERVER_MSG_TYPE_CHAT_BROADCAST = 1
SERVER_MSG_TYPE_NICKNAME_INFO = 2
SERVER_MSG_TYPE_SETTING_INFO = 3
SERVER_MSG_TYPE_HISTORY_INFO = 4